name: revive
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  easy_date_timeline: ^1.0.2
  intl: ^0.18.0
  connectivity_plus: ^5.0.2

  freezed: ^2.5.2 # to generate freezed classes, like data classes (mainly for cubit and retrofit)
  freezed_annotation: ^2.4.1 
  get_it: ^7.7.0 # for dependency injection
  json_serializable: ^6.8.0 # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_annotation: ^4.9.0 # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  dio: ^5.4.3+1 # for network requests
  retrofit: ^4.1.0 # dio client generator using source_gen.
  retrofit_generator: ^8.1.0
  pretty_dio_logger: ^1.3.1 # for logging network requests
  # localizations
  easy_localization: ^3.0.6
  # splash screen
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.9.3
  youtube_player_flutter: ^9.0.1
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  progress_border: ^0.1.5
  confetti: ^0.7.0


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Lexend
      fonts: 
        - asset: assets/fonts/LexendBold.ttf
          weight: 700
        - asset: assets/fonts/LexendMedium.ttf
          weight: 500
        - asset: assets/fonts/LexendRegular.ttf
          weight: 400
        - asset: assets/fonts/LexendSemiBold.ttf
          weight: 600
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
